$(document).ready(function() {
	$('.lp-footer')[0].addEventListener('touchstart',function(e){
		e.preventDefault()
		$('.cover').css('display','block');
		$('.left')[0].addEventListener('touchstart',function(e){
			e.preventDefault()
			if($('.left').hasClass('active')){
				location.href='lp-pay-1.html';
				$('.cover').css('display','none');
			}else{
				$('.left').toggleClass('active');
				$('.right').toggleClass('active');
			}	
		})
		$('.right')[0].addEventListener('touchstart',function(e){
			e.preventDefault()
			if($('.right').hasClass('active')){
				location.href='lp-pay-2.html';
			}else{
				$('.left').toggleClass('active');
				$('.right').toggleClass('active');
			}	
		})
	})
//	删除//支付
	let money=0;
	$('.edit')[0].addEventListener('touchstart',function(e){
		e.preventDefault()
		$('.lp-del').toggleClass('active');
		$('.lp-pay').toggleClass('active');
	})
	$('.lp-line1').each(function(index,value){
		value.addEventListener('touchstart',function(e){
			e.preventDefault()
			$(value).children('.circle').toggleClass('change');
			if(index==0){
				if($(value).children('.circle').hasClass('change')){
					money=money+569;
				}else{
					money=money-569;
				}
				console.log(money)
				
			}
			if(index==1){
				if($(value).children('.circle').hasClass('change')){
					money=money+96;
				}else{
					money=money-96;
				}
				console.log(money)
			}
			if(index==2){
				if($(value).children('.circle').hasClass('change')){
					money=money+852;
				}else{
					money=money-852;
				}
				console.log(money)
			}
			if(index==3){
				if($(value).children('.circle').hasClass('change')){
					money=money+36;
				}else{
					money=money-36;
				}
				console.log(money)
			}
			$('.all').html(function(){
				return ''+money;
			});
		})
	})
	$('.lp-del')[0].addEventListener('touchstart',function(e){
		e.preventDefault()
		$('.circle').each(function(index,value){
			if($(value).hasClass('change')){
				$(value).parent().addClass('active');
			}
		})
	})
})